[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && cd myorg && python manage.py collectstatic --noinput"

[deploy]
preDeployCommand = "cd myorg && python manage.py migrate"
startCommand = "cd myorg && gunicorn myorg.wsgi:application --bind 0.0.0.0:$PORT"
