# Generated by Django 6.0.3 on 2026-04-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_img',
            field=models.ImageField(blank=True, null=True, upload_to='issue/'),
        ),
    ]
